name: Java CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
	  env:
      env: ci
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Checkstyle with Maven
        run: mvn checkstyle:checkstyle
      - name: Test with Maven
        run: mvn test
  deploy-heroku:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cherry-surprise-04129"
          heroku_email: "christopher.godin.1@ulaval.ca"
          healthcheck: "https://cherry-surprise-04129.herokuapp.com/health"
          rollbackonhealthcheckfailed: true
          dontuseforce: false
