name: Java CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      env: ci
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Checkstyle with Maven
        run: mvn checkstyle:checkstyle --no-transfer-progress
      - name: Run test coverage
        run: mvn jacoco:prepare-agent test jacoco:report --no-transfer-progress
      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v2.7
        with:
          coverage_results_path: target/site/jacoco/jacoco.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false

      # uploads the coverage-report.md artifact
      - name: Upload Code Coverage Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report-markdown
          path: "*/coverage-results.md"
          retention-days: 1
  deploy-heroku:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cherry-surprise-04129"
          heroku_email: "christopher.godin.1@ulaval.ca"
          healthcheck: "https://cherry-surprise-04129.herokuapp.com/health"
          rollbackonhealthcheckfailed: true
          dontuseforce: false
